name: "Report an Issue"
description: "Create a bug report to help us improve the GModSCMI"
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, please do the following:
        * Try to whitelist the importer program.
        * Try verifying your Garry's Mod file integrity on Steam.
        * Try to use the provided Jigglebone and Material tools in game to fix common issues. 
  - type: textarea
    id: the-report
    attributes:
      label: Details
      description: |
        Tell us exactly what happens here, every single detail that you can think of.  
        Please include information such as the console log if possible.
      placeholder: Paste the error log here..
    validations:
      required: true
  - type: textarea
    id: model-file
    attributes:
      label: Original Model File Which Caused the Error
      description: |
        Please provide the model file if possible.
      placeholder: Please upload a .zip file containing your model.
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: Version of the game
      description: |
         Please let us know what version of the game you are running. This info can be retrieved via the `version` console command. (SHIFT+ESC to open the console in-game)  
      placeholder: Paste the output of the "version" console command here..
    validations:
      required: false
  - type: dropdown
    id: beta
    attributes:
      label: Beta
      description: What beta version of the game are you using? Ignore this if you have no idea.
      options:
        - None/Public/Default/Main
        - x86-64 beta
        - Dev beta
    validations:
      required: false
      type: dropdown
    id: OS
    attributes:
      label: OS
      description: What OS are you using?
      options:
        - Windows 11
        - Any Linux / Ubuntu
        - Windows 10
    validations:
      required: false
